export const casinoService = {
    query,
}

function query() {
    return gCasinos
}

const gCasinos = [
    {
        name: 'Fat Pirate',
        bonus: '100% up to £425 + 200 Free Spins + 1 Bonus Crab',
        wagering: '30x',
        categories: ['Slots', 'Live Casino', 'Table Games', 'Mini Games'],
        payments: ['Visa', 'MasterCard', 'Bitcoin', 'Ethereum', 'Neteller'],
        payoutSpeed: '1-3 Days',
        winningRate: '95%',
        rating: 4.9,
        numOfRates: 34,
        link: 'https://oliolaapi.com/click.php?project_id=7956c0f59e&affiliate_id=879f592217&lp=cb17863783',
        logo: 'img/casino/fatPirate.png',
    },
    {
        name: 'Gransino',
        bonus: '100% up to £425 + 200 Free spins',
        wagering: '35x',
        categories: ['Slots', 'Mini Games', 'Live Casino', 'Table Games'],
        payments: ['Visa', 'MasterCard', 'Bitcoin', 'Ethereum', 'Neteller'],
        payoutSpeed: 'Fast payout, 24-48 hours',
        winningRate: '96%-98%%',
        rating: 4.9,
        numOfRates: 29,
        link: 'https://oliolaapi.com/click.php?project_id=aa3e1423f2&affiliate_id=879f592217&lp=f19483714b',
        logo: 'img/casino/gransino1.webp',
    },
    {
        name: 'Donbet',
        bonus: '150% up to €750 + 50 Free Spins',
        wagering: '30x',
        categories: [
            'eSports',
            'Mini Games',
            'Live Casino',
            'Slots',
            'Table Games',
        ],
        payments: ['Visa', 'MasterCard', 'Bitcoin', 'Ethereum', 'Neteller'],
        payoutSpeed: '1 for crypto, 1-5 Days for e-wallets and bank transfers',
        winningRate: '95%-98%',
        rating: 4.8,
        numOfRates: 21,
        link: 'https://oliolaapi.com/click.php?project_id=a3836d211c&affiliate_id=879f592217&lp=cd8ffba994',
        logo: 'img/casino/donbet.png',
    },
    {
        name: 'Casino Lab',
        bonus: '100% up to £425 + 200 Free spins',
        wagering: '35x',
        categories: ['Slots', 'Mini Games', 'Live Casino', 'Table Games'],
        payments: ['Visa', 'MasterCard', 'Bitcoin', 'Ethereum', 'Neteller'],
        payoutSpeed: 'Fast payout, 1-3 Days',
        winningRate: '98%',
        rating: 4.8,
        numOfRates: 17,
        link: 'https://oliolaapi.com/click.php?project_id=be6986d595&affiliate_id=879f592217&lp=533372d9a9',
        logo: 'img/casino/casinoLab.webp',
    },
    {
        name: 'My Stake',
        bonus: '300% up to 1500',
        wagering: '40x',
        categories: ['Live Casino', 'Slots', 'Table Games'],
        payments: ['Credit card', 'e-wallet', 'Cryptocurrency'],
        payoutSpeed: '1-5 Days',
        winningRate: '97% for table games and slots',
        rating: 4.7,
        numOfRates: 13,
        link: 'https://Europeen777.com',
        logo: 'img/casino/myStake.jpg',
    },
]
